input {
  file {
    path => "/logs/nginx/access.log"
    start_position => "beginning"
    type => "nginx-access"
  }
  
  file {
    path => "/logs/firewall/iptables.log"
    start_position => "beginning"
    type => "iptables"
  }
}

filter {
  mutate {
    add_field => { "infrastructure" => "docker-lab" }
  }
}

output {
  stdout { codec => rubydebug }
  file {
    path => "/logs/logstash/output.json"
    codec => json_lines
  }
}
